<script>
    import SmallButton from '../../components/SmallButton.svelte';
    import ProjectCard from '../../components/ProjectCard.svelte';
    
    let activeTab = 'hardware'; // Default tab
    
    /**
   * @param {string} tab
   */
    function switchTab(tab) {
        activeTab = tab;
    }
</script>

<head>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
</head>

<svg stroke="#bac736" stroke-width="2" class="pt-6 text-line max-h-32 sm:h-30" width="100%">
    <defs>
        <linearGradient id="gradient" x1="0" x2="0" y1="0" y2="1">
            <stop offset="0%" stop-color="#f3ec78" />
            <stop offset="100%" stop-color="#af4261" />
    </defs>
    <text 
        class="text-center text-4xl sm:text-7xl md:text-7xl lg:text-7xl xs:text-5xl" 
        x="50%" 
        y="50%" 
        dominant-baseline="middle" 
        text-anchor="middle">
        Projects
    </text>
</svg>

<div class="justify-center text-center w-full py-5 space-x-4">
    <SmallButton
        label="Hardware"
        className={activeTab === 'hardware' ? 'active' : ''}
        onClick={() => switchTab('hardware')}
    />
    <SmallButton
        label="Software"
        className={activeTab === 'software' ? 'active' : ''}
        onClick={() => switchTab('software')}
    />
</div>

<div class="px-4 py-8 max-w-4xl mx-auto">
    {#if activeTab === 'hardware'}
        <h2 class="text-2xl font-mono mb-4">Hardware Projects</h2>
        <ProjectCard projectName="Cell Heat Generation" img="/BatteryTest.JPG" description="One of my new member projects for BFR my freshman year! We were tasked with finding the heat generated by the battery cells." />
    {:else}
        <div class="space-y-6 fade-in">
            <h2 class="text-2xl font-mono mb-4">Software Projects</h2>
            <!-- Add your software projects here -->
            <div class="project-card">
                <h3>Project 1</h3>
                <p>Description...</p>
            </div>
        </div>
    {/if}
</div>

<style>

    .fade-in {
        animation: fadeIn 0.3s ease-in;
    }

    @keyframes fadeIn {
        from { opacity: 0; transform: translateY(10px); }
        to { opacity: 1; transform: translateY(0); }
    }
</style>