<script>
    import Button from '../../components/Button.svelte';
    import SmallButton from '../../components/SmallButton.svelte';
    import ProjectCard from '../../components/ProjectCard.svelte';
    
    let activeTab = 'hardware'; // Default tab
    
    /**
   * @param {string} tab
   */
    function switchTab(tab) {
        activeTab = tab;
    }
</script>

<head>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
</head>

<svg stroke="#bac736" stroke-width="2" class="pt-6 text-line max-h-32 sm:h-30" width="100%">
    <defs>
        <linearGradient id="gradient" x1="0" x2="0" y1="0" y2="1">
            <stop offset="0%" stop-color="#f3ec78" />
            <stop offset="100%" stop-color="#af4261" />
    </defs>
    <text 
        class="text-center text-4xl sm:text-7xl md:text-7xl lg:text-7xl xs:text-5xl" 
        x="50%" 
        y="50%" 
        dominant-baseline="middle" 
        text-anchor="middle">
        Projects
    </text>
</svg>

<div class="justify-center text-center w-full py-5 space-x-4">
    <SmallButton
        label="Hardware"
        className={activeTab === 'hardware' ? 'active' : ''}
        onClick={() => switchTab('hardware')}
    />
    <SmallButton
        label="Software"
        className={activeTab === 'software' ? 'active' : ''}
        onClick={() => switchTab('software')}
    />
</div>

<div class="px-4 py-8 max-w-[70rem] mx-auto">
    {#if activeTab === 'hardware'}
        <div class="fade-in">
            <h2 class="text-2xl font-mono mb-4">Hardware Projects</h2>
            <div class="columns-1 sm:columns-2 gap-4 [column-fill:_balance] space-y-4">
                <ProjectCard projectName="Custom BMS" img="/BMS.png" description="A custom battery management system I am currently designing for BFR's Mk. 10. It features a distributed system of 1 motherboard and 5 daughter boards to monitor 100 cylindrical LiIon cells. To learn more, check out this <a href='https://bruinformularacing.notion.site/Custom-BMS-a13a167a22fc4f7280358c83af6a4524'>Notion page</a>." />
                <ProjectCard projectName="Cell Heat Generation" img="/BatteryTest.JPG" description="One of my new member projects for BFR my freshman year! We were tasked with finding the heat generated by the battery cells." />
            </div>
        </div>
    {:else}
        <div class="fade-in">
            <h2 class="text-2xl font-mono mb-4">Software Projects</h2>
            <div class="columns-1 sm:columns-2 gap-4 [column-fill:_balance] space-y-4">
                <ProjectCard projectName="Prospectus" img="/ProspectusHomePage.png" description="A resume-sharing website built by me and my friends. Check out the code <a href='https://github.com/aroy23/Prospectus' class='underline hover:text-gray-300'>here</a> or watch our <a href='https://www.youtube.com/watch?v=dHh1mvhMxEE'>video presentation</a>!" />
                <ProjectCard projectName="Stock Site" img="/StockSite.png" description="A stock tracking website I built for fun! It uses the Finnhub and TradingView APIs to fetch stock data and allows users search for stocks and place them in their portfolio. Create your own portfolio <a href='https://stock-site-three.vercel.app/'>here</a> or see how it was <a href='https://github.com/simonmeatball/Stock-Site'>built</a>!"/>
                <ProjectCard projectName="Idea Hacks 2025 Website" img="/IdeaHacks2025.png" description="A website I helped work on for Idea Hacks 2025, the largest hardware hackathon on the west coast hosted by UCLA. Explore it for yourself at <a href='https://ideahacks.la/'>ideahacks.la</a>"/>
            </div>
        </div>
    {/if}

    <div class="justify-center text-center w-full mt-8">
        <Button label="Return Home" href="/" />
    </div>
</div>

<style>

    .fade-in {
        animation: fadeIn 0.3s ease-in;
    }

    @keyframes fadeIn {
        from { opacity: 0; transform: translateY(10px); }
        to { opacity: 1; transform: translateY(0); }
    }
</style>