export interface ProjectLink {
  label: string;
  url: string;
}

export interface Project {
  id: string;
  category: 'hardware' | 'software';
  projectName: string;
  folder?: string;
  images: string[];
  description: string;
  detailedDescription?: string;
  tags?: string[];
  links?: ProjectLink[];
}

export type ProjectInput = Omit<Project, 'images'> & {
  images?: string[];
};

// Vite dynamic glob to discover all image assets in static/projects/
const projectImageModules = import.meta.glob<string>(
  '/static/projects/**/*.{png,jpg,jpeg,webp,svg,gif,PNG,JPG,JPEG,WEBP,SVG,GIF,avif,AVIF}',
  { eager: true, query: '?url', import: 'default' }
);

/**
 * Returns all images found in `static/projects/<folderOrId>/` as public web paths (e.g. `/projects/<folderOrId>/<filename>`).
 * Adding more images into `static/projects/<folderOrId>/` will automatically populate the carousel!
 */
export function getProjectImages(folderOrId: string, fallbackImages: string[] = []): string[] {
  const images: string[] = [];
  const folderTarget = `/projects/${folderOrId}/`;

  for (const rawPath in projectImageModules) {
    if (rawPath.includes(folderTarget)) {
      // Normalize to public browser URL by stripping leading '/static'
      const publicPath = rawPath.startsWith('/static/') ? rawPath.replace('/static', '') : rawPath;
      images.push(publicPath);
    }
  }

  // Sort alphabetically so image ordering is deterministic (e.g. 01.png, 02.png, photo.jpg)
  images.sort();

  return images.length > 0 ? images : fallbackImages;
}

export const rawProjectsData: ProjectInput[] = [
  // --- Hardware Projects ---
  {
    id: 'custom-bms',
    category: 'hardware',
    projectName: 'Custom Battery Management System (BMS)',
    description: 'A custom battery management system I designed for BFR\'s Mk. 10. It features a distributed system of 1 motherboard and 5 daughter boards to monitor 100 cylindrical 18650 Li-ion cells.',
    detailedDescription: `
      <p>The <strong>Custom Battery Management System (BMS)</strong> is designed for Bruin Formula Racing's (BFR) Mk. 10 electric vehicle. To ensure maximum safety, thermal regulation, and cell balancing for a 100-cell cylindrical Li-ion accumulator, I architected a modular distributed topology:</p>
      <ul class="list-disc list-inside space-y-2 mt-2">
        <li><strong>Motherboard Architecture:</strong> Centralized STM32 Nucleo G474RE board handling CAN bus telemetry, safety shutdown loops, and state-of-charge calculation.</li>
        <li><strong>Daughterboards:</strong> 5 daisy-chained monitoring boards utilizing ADI's ADBMS6830 IC chips to monitor the voltage and temperature data of 20 cells each.</li>
        <li><strong>Safety Isolation:</strong> Galvanic isolation between the high voltage battery and low voltage control circuits through transformers and AC coupling capacitors.</li>
      </ul>
    `,
    tags: ['KiCAD', 'PCB Design', 'Embedded C', 'ISOSPI', '18650 Cells', 'Battery Management System (BMS)'],
    links: [
      { label: 'BFR Notion Page', url: 'https://bruinformularacing.notion.site/Custom-BMS-a13a167a22fc4f7280358c83af6a4524' }
    ]
  },
  {
    id: 'cell-heat-generation',
    category: 'hardware',
    projectName: 'Cell Heat Generation',
    description: 'One of my new member projects for BFR my freshman year! We were tasked with finding the heat generated by the battery cells.',
    detailedDescription: `
      <p>As a new member project for UCLA's Bruin Formula Racing team, our team conducted empirical thermodynamic testing to measure the rate of heat generation in high-discharge cylindrical lithium-ion cells under simulated race conditions.</p>
      <ul class="list-disc list-inside space-y-2 mt-2">
        <li>Designed a controlled thermal test bench with active load discharging and thermocouple sensor arrays.</li>
        <li>Calculated internal resistance variations and total heat flux to inform accumulator cooling duct geometry.</li>
        <li>Presented findings to team leads to optimize thermal management for race day endurance runs.</li>
      </ul>
    `,
    tags: ['Thermal Analysis', 'Thermodynamics', 'Sensor Instrumentation', 'Data Analysis'],
    links: []
  },

  // --- Software Projects ---
  {
    id: 'prospectus',
    category: 'software',
    projectName: 'Prospectus',
    description: 'A resume-sharing website built by me and my friends. Check out the code or watch our video presentation!',
    detailedDescription: `
      <p><strong>Prospectus</strong> is a collaborative web platform built to help students and job seekers share resumes, receive peer feedback, and organize portfolio profiles efficiently.</p>
      <ul class="list-disc list-inside space-y-2 mt-2">
        <li>Full-stack web architecture with user authentication, secure file storage, and real-time review comments.</li>
        <li>Responsive frontend interface crafted for rapid resume upload and tag-based candidate searching.</li>
      </ul>
    `,
    tags: ['Full Stack', 'Web Development', 'UI/UX Design', 'User Auth'],
    links: [
      { label: 'GitHub Repository', url: 'https://github.com/aroy23/Prospectus' },
      { label: 'Video Demo', url: 'https://www.youtube.com/watch?v=dHh1mvhMxEE' }
    ]
  },
  {
    id: 'stock-site',
    category: 'software',
    projectName: 'Stock Site',
    description: 'A stock tracking website I built for fun! It uses the Finnhub and TradingView APIs to fetch stock data and allows users to search for stocks and place them in their portfolio.',
    detailedDescription: `
      <p><strong>Stock Site</strong> is an interactive real-time financial tracking dashboard built to monitor equities, visualize stock metrics, and manage mock portfolios.</p>
      <ul class="list-disc list-inside space-y-2 mt-2">
        <li>Integrates <strong>Finnhub API</strong> for live quote prices, market news, and company fundamentals.</li>
        <li>Embedded <strong>TradingView API</strong> widgets for dynamic technical chart plotting and timeframe toggles.</li>
        <li>Personal portfolio manager supporting custom watchlist creation and search autocomplete.</li>
      </ul>
    `,
    tags: ['Svelte', 'REST APIs', 'Finnhub API', 'TradingView', 'Vercel'],
    links: [
      { label: 'Live App', url: 'https://stock-site-three.vercel.app/' },
      { label: 'GitHub Code', url: 'https://github.com/simonmeatball/Stock-Site' }
    ]
  },
  {
    id: 'ideahacks-2025',
    category: 'software',
    projectName: 'Idea Hacks 2025 Website',
    description: 'A website I helped work on for Idea Hacks 2025, the largest hardware hackathon on the West Coast hosted by UCLA.',
    detailedDescription: `
      <p><strong>Idea Hacks</strong> is the largest hardware hackathon on the West Coast, hosted annually at UCLA. I contributed to frontend development and UI responsiveness for the official 2025 event portal.</p>
      <ul class="list-disc list-inside space-y-2 mt-2">
        <li>Built accessible schedule timelines, hacker FAQ accordions, and sponsor showcases.</li>
        <li>Optimized assets and mobile layout break-points for thousands of visiting student hackers.</li>
      </ul>
    `,
    tags: ['Web Development', 'UI Design', 'IdeaHacks', 'UCLA IEEE'],
    links: [
      { label: 'Official Website', url: 'https://ideahacks.la/' }
    ]
  }
];

// Automatically populate each project's images array from its static/projects/<folderOrId>/ directory
export const projectsData: Project[] = rawProjectsData.map(p => {
  const folder = p.folder || p.id;
  const discoveredImages = getProjectImages(folder, p.images || []);
  return {
    ...p,
    folder,
    images: discoveredImages.length > 0 ? discoveredImages : ['https://placehold.co/600x400/orange/red']
  };
});
